spring:
  application:
    name: zuul-server

zuul:
  routes:
    hello-producer:
      path: /producer/**
      serviceId: hello-producer
    hello-consumer:
      path: /consumer/**
      serviceId: hello-consumer
  prefix: /api

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8087/eureka

server:
  port: 8079

# Increase the Hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 90000


